/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author FER
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        btnAtrasmenu = new javax.swing.JButton();
        btnRecaudaciones = new javax.swing.JButton();
        btnBares = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dialogBares = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnAtrasdialogBares = new javax.swing.JButton();
        btnDetallesBar = new javax.swing.JButton();
        btnModificarBar = new javax.swing.JButton();
        btnEliminarBar = new javax.swing.JButton();
        btnAñadirBar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBar = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        detalles = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        btnModificarEmpleado = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbTitulares = new javax.swing.JTable();
        btnAgregarTitular = new javax.swing.JButton();
        btnEliminarTitular = new javax.swing.JButton();
        btnModificarTitular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        btnEliminarProducto = new javax.swing.JButton();
        btnAñadirProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        btnAtrasdetalles = new javax.swing.JButton();
        btnBaresNorte = new javax.swing.JButton();
        btnBaresSur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasmenu.setText("Atrás");
        jPanel2.add(btnAtrasmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        btnRecaudaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollars.png"))); // NOI18N
        jPanel2.add(btnRecaudaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 180, 170));

        btnBares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restaurant.png"))); // NOI18N
        jPanel2.add(btnBares, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, 170));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("RECAUDACIONES");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("BARES");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 410));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu.getContentPane());
        menu.getContentPane().setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasdialogBares.setText("Atrás");
        btnAtrasdialogBares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasdialogBaresActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtrasdialogBares, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        btnDetallesBar.setText("Detalles");
        jPanel1.add(btnDetallesBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 220, 30));

        btnModificarBar.setText("Modificar Bar");
        btnModificarBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarBarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 110, 40));

        btnEliminarBar.setText("Eliminar Bar");
        jPanel1.add(btnEliminarBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 110, 40));

        btnAñadirBar.setText("Añadir Bar");
        jPanel1.add(btnAñadirBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 240, 100, 40));

        tbBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbBar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 10, 720, 200));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bar fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 800, 370));

        javax.swing.GroupLayout dialogBaresLayout = new javax.swing.GroupLayout(dialogBares.getContentPane());
        dialogBares.getContentPane().setLayout(dialogBaresLayout);
        dialogBaresLayout.setHorizontalGroup(
            dialogBaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogBaresLayout.setVerticalGroup(
            dialogBaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setEditable(false);
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 90, -1));

        jTextField8.setEditable(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbEmpleado);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 190));

        btnAgregarEmpleado.setText("Agregar Empleado");
        jPanel3.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        btnEliminarEmpleado.setText("Eliminar Empleado");
        jPanel3.add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        btnModificarEmpleado.setText("Modificar Empleado");
        jPanel3.add(btnModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel18.setText("Licencia:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 20));

        jLabel17.setText("Restaurante:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 330));

        jTabbedPane1.addTab("Empleados", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTitulares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbTitulares);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 200));

        btnAgregarTitular.setText("Agregar Titular");
        jPanel4.add(btnAgregarTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        btnEliminarTitular.setText("Eliminar Títular");
        jPanel4.add(btnEliminarTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        btnModificarTitular.setText("Modificar Titular");
        jPanel4.add(btnModificarTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel5.setText("Restaurante:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 20));

        jTextField1.setEditable(false);
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 100, -1));

        jLabel9.setText("Licencia:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, 20));

        jTextField2.setEditable(false);
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 100, -1));

        jTabbedPane1.addTab("Titulares", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbProductos);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 220));

        btnEliminarProducto.setText("Eliminar Producto");
        jPanel5.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        btnAñadirProducto.setText("Añadir Producto");
        jPanel5.add(btnAñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 110, -1));

        btnModificarProducto.setText("Modificar Producto");
        jPanel5.add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 130, -1));

        jLabel4.setText("Restaurante:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        jTextField5.setEditable(false);
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, -1));

        jLabel6.setText("Licencia:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 20));

        jTextField6.setEditable(false);
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 110, -1));

        jTabbedPane1.addTab("Inventario", jPanel5);

        btnAtrasdetalles.setText("Atrás");

        javax.swing.GroupLayout detallesLayout = new javax.swing.GroupLayout(detalles.getContentPane());
        detalles.getContentPane().setLayout(detallesLayout);
        detallesLayout.setHorizontalGroup(
            detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtrasdetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        detallesLayout.setVerticalGroup(
            detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtrasdetalles)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        btnBaresNorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bares.png"))); // NOI18N
        btnBaresNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaresNorteActionPerformed(evt);
            }
        });

        btnBaresSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/baress.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BARES DEL NORTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BARES DEL SUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(btnBaresNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBaresSur, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBaresSur, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaresNorte, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaresNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaresNorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaresNorteActionPerformed

    private void btnModificarBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarBarActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btnAtrasdialogBaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasdialogBaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasdialogBaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarEmpleado;
    public javax.swing.JButton btnAgregarTitular;
    public javax.swing.JButton btnAtrasdetalles;
    public javax.swing.JButton btnAtrasdialogBares;
    public javax.swing.JButton btnAtrasmenu;
    public javax.swing.JButton btnAñadirBar;
    public javax.swing.JButton btnAñadirProducto;
    public javax.swing.JButton btnBares;
    public javax.swing.JButton btnBaresNorte;
    public javax.swing.JButton btnBaresSur;
    public javax.swing.JButton btnDetallesBar;
    public javax.swing.JButton btnEliminarBar;
    public javax.swing.JButton btnEliminarEmpleado;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnEliminarTitular;
    public javax.swing.JButton btnModificarBar;
    public javax.swing.JButton btnModificarEmpleado;
    public javax.swing.JButton btnModificarProducto;
    public javax.swing.JButton btnModificarTitular;
    public javax.swing.JButton btnRecaudaciones;
    private javax.swing.JDialog detalles;
    private javax.swing.JDialog dialogBares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    private javax.swing.JDialog menu;
    public javax.swing.JTable tbBar;
    public javax.swing.JTable tbEmpleado;
    public javax.swing.JTable tbProductos;
    public javax.swing.JTable tbTitulares;
    // End of variables declaration//GEN-END:variables
}
